plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dailymoneydiary.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.dailymoneydiary.app'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    sourceSets {
        main {
            assets.srcDirs = ["$rootDir"]
            assets.includes = ["index.html"]
        }
    }
}

dependencies {
}
